### PR TITLE
chore add CAB signoff for SIP-023

### PR DESCRIPTION
**Pull request by wileyj**
Adding signoff line to SIP-023

### CODE REVIEW

**Comment by MarvinJanssen** [comment]
If the editors CABs feel confident then you can also use the PR to update the status to Recommended. But ideally we want a separate PR from editors to bring it to Accepted.

**Comment by whoabuddy** [comment]
> If the editors CABs feel confident then you can also use the PR to update the status to Recommended. But ideally we want a separate PR from editors to bring it to Accepted.

This makes sense, on SIP-022 we settled on a nice flow for each group to interact with the [SIP flow here](https://github.com/stacksgov/sips/blob/main/sips/sip-000/sip-000-stacks-improvement-proposal-process.md#sip-workflow-1).

Process so far as it relates to GitHub:

- SIP editors will reply on the SIP PR, and when it's ready, change status to `Accepted` through a PR
- CAB members will submit their meeting notes / vote outcomes as a PR per CAB
- upon approval from the CABs, add sign-offs and change status to `Recommended` through a PR
- upon approval from the Steering Committee, add sign-offs and change status to `Activation-in-Progress` (also want to update the readme here with new SIP number)

Noting there's a GitHub label for each status change as well.

cc @Hero-Gamer so we don't lose this info :slightly_smiling_face:

**Review by whoabuddy — APPROVED** [review]

**Comment by MarvinJanssen** [comment]
Thanks @whoabuddy. That sounds great. Right now SIP-023 has a draft status and CAB sign-offs on the main branch. Can we get editors to open a PR to prepend to the sign-off and change the status to `Accepted`? Perhaps we can move to `Recommend` on the same branch and reference this PR. I'm ready to sign off and change the status to `Activation-in-Progress` once the aforementioned is done.

**Comment by whoabuddy** [comment]
@MarvinJanssen passed this along to @Hero-Gamer to see who in the SIP editor group would feel comfortable doing so!

**Comment by Hero-Gamer** [comment]
SIP Editor @rafaelcr will be submitting PR to change status to Accepted from Draft.
Anything please ask him for this time round!

**Pull request merged**
