### PR TITLE
chore: add SIP-021 to the readme

### PR DESCRIPTION
**Pull request by obycode**

### CODE REVIEW

**Review by wileyj — APPROVED** [review]

**Review by 314159265359879 — APPROVED** [review]
LGTM

**Review by diwakergupta — APPROVED** [review]

**Review by wileyj — APPROVED** [review]

**Comment by diwakergupta** [comment]
@wileyj who else has write access in this repo? I don't apparently, so my approval doesn't count :/

**Comment by wileyj** [comment]
> @wileyj who else has write access in this repo? I don't apparently, so my approval doesn't count :/

todo: update who has access here. added rafael and will for now. i'll send you an invite too

**Review by rafaelcr — APPROVED** [review]
LGTM

**Pull request merged**
